stages:
  - build
  - deploy

variables:

  #GLOBAL
  IMAGE_NAME: ssv-liquidator

  #PRODUCTION
  ACCOUNT_ID_INFRA_PROD: 764289642555
  AWS_REGION_INFRA_PROD: "us-west-2"
  DOCKER_REPO_INFRA_PROD: $ACCOUNT_ID_INFRA_PROD.dkr.ecr.$AWS_REGION_INFRA_PROD.amazonaws.com/$IMAGE_NAME
  APP_REPLICAS_INFRA_PROD: "1"
  ECRLOGIN_INFRA_PROD: "aws ecr get-login --registry-ids $ACCOUNT_ID_INFRA_PROD --region $AWS_REGION_INFRA_PROD --no-include-email"

#blox-infra-prod
Build prod Docker image:
  stage: build
  tags:
    - blox-infra-prod
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHA -f Dockerfile .
    - DOCKER_LOGIN_TO_INFRA_PROD_REPO=`$ECRLOGIN_INFRA_PROD`
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHA $DOCKER_REPO_INFRA_PROD:$CI_COMMIT_SHA
    - $DOCKER_LOGIN_TO_INFRA_PROD_REPO && docker push $DOCKER_REPO_INFRA_PROD:$CI_COMMIT_SHA
  only:
    - main

Helm deploy on production:
  stage: deploy
  tags:
    - blox-infra-prod
  image: devth/helm:v3.3.4
  script:
    - mkdir ~/.kube/
    - echo $PROD_KUBECONFIG | base64 -d > kubeconfig
    - mv kubeconfig ~/.kube/
    - export KUBECONFIG=~/.kube/kubeconfig
    - kubectl config get-contexts
    - IMAGE_TAG=$CI_COMMIT_SHA
    - helm upgrade
      --install
      --namespace liquidation
      --set image.tag=$IMAGE_TAG
      --values .k8/helm3/ssv-liquidator/prod-values.yaml
      --wait
      ssv-liquidator
      .k8/helm3/ssv-liquidator/
  only:
     - main      
