{
 "title": "SSV liquidation",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "liquidator-prater-jato-v2-1-svc.liquidation:80"
   }
  ]
 },
 "panels": [
  { "title": "LIQUIDATOR METRICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last synced block number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lastBlockNumberMetric{app=\"liquidation-cli\",instance=~\"$instance.*\",job=\"ssv-liquidator\"} ",
     "legendFormat": "lastBlockNumber"
    }
   ]
  },
  {
   "title": "Liquidator ETH Balance",
   "type": "stat",
   "description": "Current balance of the wallet of the liquidator",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "liquidatorETHBalance{app=\"liquidation-cli\",instance=~\"$instance.*\",job=\"ssv-liquidator\"}\t",
     "legendFormat": "liquidatorETHBalance"
    }
   ]
  },
  {
   "title": "Active clusters",
   "type": "stat",
   "description": "Total active clusters count",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "totalActiveClusters{app=\"liquidation-cli\",instance=~\"$instance.*\",job=\"ssv-liquidator\"}",
     "legendFormat": "totalActiveClusters"
    }
   ]
  },
  {
   "title": "Liquidatable clusters",
   "type": "stat",
   "description": "Total liquidatable clusters count",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "totalLiquidatableClusters{app=\"liquidation-cli\",instance=~\"$instance.*\",job=\"ssv-liquidator\"} ",
     "legendFormat": "totalLiquidatableClusters"
    }
   ]
  },
  {
   "title": "Liq Collateral 10% burnt",
   "type": "stat",
   "description": "Clusters gone through 10% of their liquidation collateral counter",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "burnt10LiquidatableClusters{app=\"liquidation-cli\",instance=~\"$instance.*\",job=\"ssv-liquidator\"} ",
     "legendFormat": "burnt10LiquidatableClusters"
    }
   ]
  },
  {
   "title": "Liq Collateral 50% burnt",
   "type": "stat",
   "description": "Clusters gone through 50% of their liquidation collateral counter",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "burnt50LiquidatableClusters{app=\"liquidation-cli\",instance=~\"$instance.*\",job=\"ssv-liquidator\"} ",
     "legendFormat": "burnt50LiquidatableClusters"
    }
   ]
  },
  {
   "title": "Liq Collateral 90% burnt",
   "type": "stat",
   "description": "Clusters gone through 90% of their liquidation collateral counter",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "burnt90LiquidatableClusters{app=\"liquidation-cli\",instance=~\"$instance.*\",job=\"ssv-liquidator\"} ",
     "legendFormat": "burnt90LiquidatableClusters"
    }
   ]
  },
  {
   "title": "Liq Collateral 99% burnt",
   "type": "stat",
   "description": "Clusters gone through 99% of their liquidation collateral counter",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "burnt99LiquidatableClusters{app=\"liquidation-cli\",instance=~\"$instance.*\",job=\"ssv-liquidator\"} ",
     "legendFormat": "burnt99LiquidatableClusters"
    }
   ]
  },
  { "title": "POD METRICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "SSV liquidator CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(\n      rate(container_cpu_usage_seconds_total{pod=~\"liquidator-prater-jato-v2-1-.*\"}[1m])\n    ) by (pod, container_name, namespace, slave)\n      /\n    sum(\n      kube_pod_container_resource_limits{pod=~\"liquidator-prater-jato-v2-1-.*\", resource=\"cpu\"}\n    ) by (pod, container_name, namespace, slave)\n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "SSV Liquidators Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",pod=~\"liquidator-prater-jato-v2-1-.*\", container=\"liquidator-prater-jato-v2-1\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "SSV Liquidators pod state",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"liquidator-prater-jato-v2-1\",namespace=\"liquidation\",pod=~\"liquidator-prater-jato-v2-1-.*\",service=\"prometheus-operator-kube-state-metrics\"}",
     "legendFormat": "liquidator-prater-jato-v2-1"
    }
   ]
  },
  { "title": "ALERTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Last synced block number Alert",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "changes(lastBlockNumberMetric{app=\"liquidation-cli\",instance=\"liquidator-prater-jato-v2-1-svc.liquidation:80\",job=\"ssv-liquidator\"}[2m])",
     "legendFormat": "liquidator-prater-jato-v2-1"
    }
   ]
  },
  {
   "title": "Liquidator ETH Balance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "liquidatorETHBalance{app=\"liquidation-cli\",instance=\"liquidator-prater-jato-v2-1-svc.liquidation:80\",job=\"ssv-liquidator\"}\t",
     "legendFormat": "liquidatorETHBalance"
    }
   ]
  },
  {
   "title": "Liquidatable clusters",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "totalLiquidatableClusters{app=\"liquidation-cli\",instance=\"liquidator-prater-jato-v2-1-svc.liquidation:80\",job=\"ssv-liquidator\"} ",
     "legendFormat": "liquidator-prater-jato-v2-1"
    }
   ]
  },
  {
   "title": "Liq Collateral 10% burnt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "burnt10LiquidatableClusters{app=\"liquidation-cli\",instance=\"liquidator-prater-jato-v2-1-svc.liquidation:80\",job=\"ssv-liquidator\"} ",
     "legendFormat": "burnt10LiquidatableClusters"
    }
   ]
  },
  {
   "title": "Liq Collateral 50% burnt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "burnt50LiquidatableClusters{app=\"liquidation-cli\",instance=\"liquidator-prater-jato-v2-1-svc.liquidation:80\",job=\"ssv-liquidator\"} ",
     "legendFormat": "burnt50LiquidatableClusters"
    }
   ]
  },
  {
   "title": "Liq Collateral 90% burnt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "burnt90LiquidatableClusters{app=\"liquidation-cli\",instance=\"liquidator-prater-jato-v2-1-svc.liquidation:80\",job=\"ssv-liquidator\"} ",
     "legendFormat": "burnt90LiquidatableClusters"
    }
   ]
  },
  {
   "title": "Liq Collateral 99% burnt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "burnt99LiquidatableClusters{app=\"liquidation-cli\",instance=\"liquidator-prater-jato-v2-1-svc.liquidation:80\",job=\"ssv-liquidator\"} ",
     "legendFormat": "burnt99LiquidatableClusters"
    }
   ]
  },
  {
   "title": "DEVELOPER METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Critical status",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "criticalStatus{app=\"liquidation-cli\",instance=~\"$instance.*\",job=\"ssv-liquidator\"} "
      }
     ]
    },
    {
     "title": "Critical Status",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 21, "x": 3, "y": 41 },
     "targets": [
      {
       "expr": "criticalStatus{app=\"liquidation-cli\",instance=~\"$instance.*\",job=\"ssv-liquidator\"} ",
       "legendFormat": "criticalStatus"
      }
     ]
    },
    {
     "title": "Fetch Task Health",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fetchStatus{app=\"liquidation-cli\",instance=~\"$instance.*\",job=\"ssv-liquidator\"}"
      }
     ]
    },
    {
     "title": "Fetch Task Health",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 21, "x": 3, "y": 46 },
     "targets": [
      {
       "expr": "fetchStatus{app=\"liquidation-cli\",instance=~\"$instance.*\",job=\"ssv-liquidator\"}",
       "legendFormat": "fetchStatus"
      }
     ]
    },
    {
     "title": "Burn Rates Task Health",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "burnRatesStatus{app=\"liquidation-cli\",instance=~\"$instance.*\",job=\"ssv-liquidator\"}"
      }
     ]
    },
    {
     "title": "Burn Rates Task Health",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 21, "x": 3, "y": 51 },
     "targets": [
      {
       "expr": "burnRatesStatus{app=\"liquidation-cli\",instance=~\"$instance.*\",job=\"ssv-liquidator\"} ",
       "legendFormat": "burnRatesStatus"
      }
     ]
    },
    {
     "title": "Liquidation Task Health",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "liquidationStatus{app=\"liquidation-cli\",instance=~\"$instance.*\",job=\"ssv-liquidator\"}"
      }
     ]
    },
    {
     "title": "Liquidation Task Health",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 21, "x": 3, "y": 56 },
     "targets": [
      {
       "expr": "liquidationStatus{app=\"liquidation-cli\",instance=~\"$instance.*\",job=\"ssv-liquidator\"} ",
       "legendFormat": "liquidationStatus"
      }
     ]
    }
   ]
  }
 ]
}